version: "3.4"

services:
  miservicio_mysql:
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: ./MySql
    #      target: mimysqlcom
    volumes:
      - /mysql-db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  miservicio_php:
    build:
      context: ./ApachePhp
    #      target: miapachephpcom
    volumes:
      - ./../:/var/www/html
    links:
      - miservicio_mysql:elalias
    ports:
      - 80:80
    depends_on:
      - miservicio_mysql

volumes:
  mysql-db-data: